### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by chbndrhnns** [floross/docker-readthedocs#1]
When I enable elasticsearch, redis and postgresql and do a ```docker-compose up```, the following error occurs:

```
readthedocs_1    | 2017-01-19 13:52:11,322 INFO spawned: 'readthedocs-web' with pid 23
readthedocs_1    | 2017-01-19 13:52:11,322 INFO spawnerr: can't find command '/app/bin/rtd-provision.sh'
readthedocs_1    | Traceback (most recent call last):
readthedocs_1    |   File "manage.py", line 11, in <module>
readthedocs_1    |     execute_from_command_line(sys.argv)
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
readthedocs_1    |     utility.execute()
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
readthedocs_1    |     django.setup()
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
readthedocs_1    |     apps.populate(settings.INSTALLED_APPS)
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
readthedocs_1    |     app_config = AppConfig.create(entry)
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
readthedocs_1    |     module = import_module(entry)
readthedocs_1    |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
readthedocs_1    |     __import__(name)
readthedocs_1    | ImportError: No module named django_countries
readthedocs_1    | 2017-01-19 13:52:11,667 INFO exited: readthedocs-web (exit status 1; not expected)
```

**Comment by rasky** [comment]
Same issue. Any workaround @chbndrhnns ?

**Comment by chbndrhnns** [comment]
@rasky: I gave up, so no, sorry. Let me know if you find something out.

**Comment by floross** [comment]
Sorry guys, when I did this container, elasticsearch was not tested and not intended to work. If you want to make a pull request, I'll accepted it rapidly.

**Comment by Jmennius** [comment]
ES should be working out-of-box with current master (see #4).
Please comment if you experience any issues.
